<a href="https://colab.research.google.com/github/Jeevaganesh04/Python-Practice/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

data = {
    'Name':['Tony','Saul','Jax'],
    'Age':[50,45,30],
    'City':['New Jersey','New Mexico','California']
}

df = pd.DataFrame(data)

df['Job']=['Waste Management','Lawyer','Outlaw']

print(df)

   Name  Age        City               Job
0  Tony   50  New Jersey  Waste Management
1  Saul   45  New Mexico            Lawyer
2   Jax   30  California            Outlaw


In [10]:
import pandas as pd

data = {
    'Name': ['John', 'Emma', 'Liam', None],
    'Age': [28, None, 24, 30],
    'Salary': [45000, 52000, None, 60000]
}
df = pd.DataFrame(data)

df['Age'] = df['Age'].fillna(df['Age'].mean())

df.dropna(subset=['Name'], inplace=True)

print(df)


   Name        Age   Salary
0  John  28.000000  45000.0
1  Emma  27.333333  52000.0
2  Liam  24.000000      NaN


In [12]:
import pandas as pd

data = {
    'Name': ['John', 'Emma', 'Liam', None],
    'Age': [28, None, 24, 30],
    'Salary': [45000, 52000, None, 60000]
}
df = pd.DataFrame(data)

f1=df[df['Age']<30]
f2=df[(df['Salary']>=45000) & (df['Salary']<60000)]

print(f1)
print(f2)

   Name   Age   Salary
0  John  28.0  45000.0
2  Liam  24.0      NaN
   Name   Age   Salary
0  John  28.0  45000.0
1  Emma   NaN  52000.0


In [15]:
import pandas as pd

data = {
    'Name': ['John', 'Emma', 'Liam', None],
    'Age': [28, None, 24, 30],
    'Salary': [45000, 52000, None, 60000],
    'Department':['IT','HR','TS','MANAGER']
}
df = pd.DataFrame(data)
df['Salary']=df['Salary'].fillna(0)
grp = df.groupby('Department')['Salary'].mean()

print(grp)

Department
HR         52000.0
IT         45000.0
MANAGER    60000.0
TS             0.0
Name: Salary, dtype: float64


In [17]:
import numpy as np

arr=(np.random.randint(1,100,(3,3)))
print(arr)

[[48 79 81]
 [17 67 40]
 [83 85 97]]


In [20]:
import numpy as np

arr1=np.array([34,67,21])
arr2=np.array([87,25,59])

print('Addition: ',arr1+arr2)
print('Subtraction: ',arr1-arr2)
print('Division: ',arr1/arr2)
print('Multiplication: ',arr1*arr2)

Addition:  [121  92  80]
Subtraction:  [-53  42 -38]
Division:  [0.3908046 2.68      0.3559322]
Multiplication:  [2958 1675 1239]


In [3]:
from sklearn.linear_model import LinearRegression
import numpy as np

data={
    'Size (sqft)':[1000,1500,2000,2500,3000],
    'Price ($)':[300000,400000,500000,600000,700000]
}

X=np.array(data['Size (sqft)']).reshape(-1,1)
y=np.array(data['Price ($)'])

model=LinearRegression()
model.fit(X,y)

price=model.predict([[2200]])
print(f"{price[0]:,.2f}")

540,000.00


In [5]:
from sklearn.tree import DecisionTreeClassifier
import pandas as pd

data = {
    'Attendance':[85,60,75,90,40],
    'Study Hours':[10,3,7,15,2],
    'Previous Score':[70,50,65,80,30],
    'Pass/Fail':[1,0,1,1,0]
}

df=pd.DataFrame(data)

X=df[['Attendance','Study Hours','Previous Score']]
y=df[['Pass/Fail']]

model=DecisionTreeClassifier()
model.fit(X,y)

predict=model.predict(X)
print(predict)

[1 0 1 1 0]
